//
// Created by ktr on 29.05.2017.
//

#ifndef JIMP_EXERCISES_SEQUENTIALGENERATOR_H
#define JIMP_EXERCISES_SEQUENTIALGENERATOR_H


class SequentialGenerator {

};


#endif //JIMP_EXERCISES_SEQUENTIALGENERATOR_H
